#!/bin/bash

# Create directory for weapon images
mkdir -p ../assets/images/weapons

# Function to download a weapon image
download_weapon() {
    local weapon_id="$1"
    local image_url="$2"
    local filename="../assets/images/weapons/${weapon_id}.png"
    
    echo "Downloading $weapon_id..."
    curl -s -L "$image_url" -o "$filename"
    
    if [ -f "$filename" ] && [ -s "$filename" ]; then
        echo "✓ Downloaded $weapon_id"
    else
        echo "✗ Failed to download $weapon_id"
        rm -f "$filename"
    fi
}

# Based on the patterns I found, here are direct URLs for some weapons
# Format: weapon_id|image_url

weapons=(
    "dagger|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Wpn_Dagger.png"
    "club|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Club.png"
    "mace|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Mace.png"
    "morning-star|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Morning_Star.png"
    "reinforced-club|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Reinforced_Club.png"
    "warpick|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Warpick.png"
    "blacksmiths-hammer|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Blacksmith_Hammer.png"
    "hammer-of-vamos|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Hammer_of_Vamos.png"
    "great-club|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Great_Club.png"
    "large-club|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Large_Club.png"
    "grants|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Grant.png"
    "demons-great-hammer|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Demon's_Great_Hammer.png"
    "dragon-tooth|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dragon_Tooth.png"
    "smoughs-hammer|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Smough's_Hammer.png"
    "zweihander|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Zweihander.png"
    "claymore|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Claymore.png"
    "bastard-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Bastard_Sword.png"
    "greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Greatsword.png"
    "uchigatana|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Uchigatana.png"
    "iaito|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Iaito.png"
    "washing-pole|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Washing_Pole.png"
    "chaos-blade|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Chaos_Blade.png"
    "longsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Long_Sword.png"
    "shortsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Shortsword.png"
    "broadsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Broadsword.png"
    "broken-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Broken_Straight_Sword.png"
    "straight-sword-hilt|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Straight_Sword_Hilt.png"
    "balder-side-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Balder_Side_Sword.png"
    "crystal-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Crystal_Straight_Sword.png"
    "sunlight-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Sunlight_Straight_Sword.png"
    "barbed-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Barbed_Straight_Sword.png"
    "silver-knight-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Silver_Knight_Straight_Sword.png"
    "astoras-straight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Astora's_Straight_Sword.png"
    "drake-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Drake_Sword.png"
    "darksword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Darksword.png"
    "black-knight-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Black_Knight_Sword.png"
    "flamberge|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Flamberge.png"
    "crystal-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Crystal_Greatsword.png"
    "moonlight-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Moonlight_Greatsword.png"
    "greatsword-of-artorias|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Greatsword_of_Artorias.png"
    "stone-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Stone_Greatsword.png"
    "abyss-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Abyss_Greatsword.png"
    "mans-serpent-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Man-Serpent_Greatsword.png"
    "obsidian-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Obsidian_Greatsword.png"
    "great-lord-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Great_Lord_Greatsword.png"
    "demon-great-machete|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Demon_Great_Machete.png"
    "dragon-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dragon_Greatsword.png"
    "black-knight-greatsword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Black_Knight_Greatsword.png"
    "rapier|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Rapier.png"
    "estoc|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Estoc.png"
    "mail-breaker|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Mail_Breaker.png"
    "ricards-rapier|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Ricard's_Rapier.png"
    "velkas-rapier|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Velka's_Rapier.png"
    "hand-axe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Hand_Axe.png"
    "battle-axe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Battle_Axe.png"
    "crescent-axe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Crescent_Axe.png"
    "greataxe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Greataxe.png"
    "butcher-knife|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Butcher_Knife.png"
    "golem-axe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Golem_Axe.png"
    "gargoyle-tail-axe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Gargoyle_Tail_Axe.png"
    "demons-greataxe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Demon's_Greataxe.png"
    "dragon-king-greataxe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dragon_King_Greataxe.png"
    "black-knight-greataxe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Black_Knight_Greataxe.png"
    "scimitar|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Scimitar.png"
    "falchion|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Falchion.png"
    "shotel|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Shotel.png"
    "painting-guardian-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Painting_Guardian_Sword.png"
    "quelaags-furysword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Quelaag's_Furysword.png"
    "jagged-ghost-blade|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Jagged_Ghost_Blade.png"
    "ghost-blade|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Ghost_Blade.png"
    "server|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Server.png"
    "murakumo|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Murakumo.png"
    "gravelord-sword|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Gravelord_Sword.png"
    "parrying-dagger|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Parrying_Dagger.png"
    "bandits-knife|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Bandit's_Knife.png"
    "priscillas-dagger|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Priscilla's_Dagger.png"
    "dark-silver-tracer|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dark_Silver_Tracer.png"
    "spear|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Spear.png"
    "winged-spear|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Winged_Spear.png"
    "pike|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Pike.png"
    "partisan|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Partisan.png"
    "demons-spear|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Demon's_Spear.png"
    "dragonslayer-spear|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dragonslayer_Spear.png"
    "silver-knight-spear|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Silver_Knight_Spear.png"
    "moonlight-butterfly-horn|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Moonlight_Butterfly_Horn.png"
    "channelers-trident|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Channeler's_Trident.png"
    "halberd|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Halberd.png"
    "gargoyle-halberd|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Gargoyle's_Halberd.png"
    "scythe|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Scythe.png"
    "lucerne|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Lucerne.png"
    "giants-halberd|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Giant's_Halberd.png"
    "titanite-catch-pole|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Titanite_Catch_Pole.png"
    "black-knight-halberd|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Black_Knight_Halberd.png"
    "caestus|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Caestus.png"
    "claw|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Claw.png"
    "dragon-bone-fist|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dragon_Bone_Fist.png"
    "dark-hand|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Dark_Hand.png"
    "whip|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Whip.png"
    "notched-whip|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Notched_Whip.png"
    "short-bow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Short_Bow.png"
    "longbow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Long_Bow.png"
    "composite-bow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Composite_Bow.png"
    "black-bow-of-pharis|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Black_Bow_of_Pharis.png"
    "light-crossbow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Light_Crossbow.png"
    "heavy-crossbow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Heavy_Crossbow.png"
    "sniper-crossbow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Sniper_Crossbow.png"
    "avelyn|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Avelyn.png"
    "sorcerers-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Sorcerer's_Catalyst.png"
    "tin-crystallization-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Tin_Crystallization_Catalyst.png"
    "logans-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Logan's_Catalyst.png"
    "tin-banishment-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Tin_Banishment_Catalyst.png"
    "oolacile-ivory-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Oolacile_Ivory_Catalyst.png"
    "manus-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Manus_Catalyst.png"
    "tin-darkmoon-catalyst|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Tin_Darkmoon_Catalyst.png"
    "talisman|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Talisman.png"
    "canvas-talisman|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Canvas_Talisman.png"
    "darkmoon-talisman|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Darkmoon_Talisman.png"
    "pyromancy-flame|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Pyromancy_Flame.png"
    "four-pronged-plow|https://darksouls.wiki.fextralife.com/file/Dark-Souls/Four-Pronged_Plow.png"
)

# Download each weapon image
for weapon in "${weapons[@]}"; do
    IFS='|' read -r weapon_id image_url <<< "$weapon"
    download_weapon "$weapon_id" "$image_url"
done

echo ""
echo "Download complete!"
echo "Images saved to: ../assets/images/weapons/"